"""Instrument universe + symbol/sector mapping.

Loading priority (first match wins):
  1. data/instruments.json  — generated by scripts/seed_instruments.py
  2. data/instruments.csv   — raw Upstox instruments CSV (downloaded)
  3. Hardcoded NIFTY 50 fallback (covers the 50 most liquid stocks)

Sector map priority:
  1. data/sector_map.csv    — two columns: symbol, sector
  2. Hardcoded NIFTY 50 sector table

Run `python scripts/seed_instruments.py` once to bootstrap the full universe.
"""
from __future__ import annotations

import csv
import json
from functools import lru_cache
from pathlib import Path

_DATA = Path(__file__).parent.parent.parent / "data"

# ---------------------------------------------------------------------------
# Hardcoded NIFTY 50 fallback (instrument_key, tradingsymbol, sector).
# Upstox instrument_key format: {exchange}_{segment}|{isin}
# For live use, run seed_instruments.py to get the complete universe.
# ---------------------------------------------------------------------------
_NIFTY50_FALLBACK: list[tuple[str, str, str]] = [
    # (instrument_key,              symbol,         sector)
    ("NSE_EQ|INE002A01018",  "NSE:RELIANCE",   "Energy"),
    ("NSE_EQ|INE040A01034",  "NSE:HDFCBANK",   "Financials"),
    ("NSE_EQ|INE009A01021",  "NSE:INFY",       "IT"),
    ("NSE_EQ|INE467B01029",  "NSE:TCS",        "IT"),
    ("NSE_EQ|INE090A01021",  "NSE:ICICIBANK",  "Financials"),
    ("NSE_EQ|INE238A01034",  "NSE:AXISBANK",   "Financials"),
    ("NSE_EQ|INE018A01030",  "NSE:LT",         "Industrials"),
    ("NSE_EQ|INE101A01026",  "NSE:BAJFINANCE", "Financials"),
    ("NSE_EQ|INE585B01010",  "NSE:BHARTIARTL", "Telecom"),
    ("NSE_EQ|INE154A01025",  "NSE:ITC",        "FMCG"),
    ("NSE_EQ|INE160A01022",  "NSE:HCLTECH",    "IT"),
    ("NSE_EQ|INE081A01020",  "NSE:NESTLEIND",  "FMCG"),
    ("NSE_EQ|INE214T01019",  "NSE:HINDUNILVR", "FMCG"),
    ("NSE_EQ|INE0J1Y01017",  "NSE:ADANIENT",   "Industrials"),
    ("NSE_EQ|INE423A01024",  "NSE:WIPRO",      "IT"),
    ("NSE_EQ|INE364U01010",  "NSE:ADANIPORTS", "Industrials"),
    ("NSE_EQ|INE066A01021",  "NSE:SUNPHARMA",  "Pharma"),
    ("NSE_EQ|INE021A01026",  "NSE:MARUTI",     "Auto"),
    ("NSE_EQ|INE030A01027",  "NSE:BAJAJ-AUTO", "Auto"),
    ("NSE_EQ|INE0TD00013",   "NSE:ONGC",       "Energy"),
    ("NSE_EQ|INE0CJ01017",   "NSE:BPCL",       "Energy"),
    ("NSE_EQ|INE019A01038",  "NSE:TITAN",      "Consumer"),
    ("NSE_EQ|INE528G01035",  "NSE:POWERGRID",  "Utilities"),
    ("NSE_EQ|INE752E01010",  "NSE:NTPC",       "Utilities"),
    ("NSE_EQ|INE115A01026",  "NSE:COALINDIA",  "Materials"),
    ("NSE_EQ|INE562A01011",  "NSE:TATASTEEL",  "Materials"),
    ("NSE_EQ|INE148A01028",  "NSE:JSWSTEEL",   "Materials"),
    ("NSE_EQ|INE245A01021",  "NSE:TATAMOTORS", "Auto"),
    ("NSE_EQ|INE111A01025",  "NSE:M&M",        "Auto"),
    ("NSE_EQ|INE001A01036",  "NSE:HEROMOTOCO", "Auto"),
    ("NSE_EQ|INE406A01037",  "NSE:EICHERMOT",  "Auto"),
    ("NSE_EQ|INE012A01025",  "NSE:SBILIFE",    "Insurance"),
    ("NSE_EQ|INE547C01019",  "NSE:HDFCLIFE",   "Insurance"),
    ("NSE_EQ|INE103A01014",  "NSE:TECHM",      "IT"),
    ("NSE_EQ|INE176A01028",  "NSE:HINDALCO",   "Materials"),
    ("NSE_EQ|INE775B01062",  "NSE:ULTRACEMCO", "Materials"),
    ("NSE_EQ|INE695A01028",  "NSE:GRASIM",     "Materials"),
    ("NSE_EQ|INE002S01010",  "NSE:DIVISLAB",   "Pharma"),
    ("NSE_EQ|INE318A01026",  "NSE:DRREDDY",    "Pharma"),
    ("NSE_EQ|INE215A01012",  "NSE:CIPLA",      "Pharma"),
    ("NSE_EQ|INE683A01023",  "NSE:APOLLOHOSP", "Healthcare"),
    ("NSE_EQ|INE0B9A01018",  "NSE:ASIANPAINT", "Consumer"),
    ("NSE_EQ|INE301A01014",  "NSE:PIDILITIND", "Materials"),
    ("NSE_EQ|INE765G01017",  "NSE:INDUSINDBK", "Financials"),
    ("NSE_EQ|INE0G9A01021",  "NSE:KOTAKBANK",  "Financials"),
    ("NSE_EQ|INE070A01015",  "NSE:SBIN",       "Financials"),
    ("NSE_EQ|INE860A01027",  "NSE:BAJAJFINSV", "Financials"),
    ("NSE_EQ|INE038A01020",  "NSE:BRITANNIA",  "FMCG"),
    ("NSE_EQ|INE117A01022",  "NSE:TATACONSUM", "FMCG"),
    ("NSE_EQ|INE242A01010",  "NSE:SHRIRAMFIN", "Financials"),
]


@lru_cache
def _load_json() -> dict:
    """Load instruments.json produced by seed_instruments.py."""
    p = _DATA / "instruments.json"
    if not p.exists():
        return {}
    with p.open() as f:
        return json.load(f)


@lru_cache
def sector_map() -> dict[str, str]:
    """symbol -> sector string.

    Loads from data/sector_map.csv if available, otherwise uses the
    hardcoded NIFTY 50 table. The full map is generated by seed_instruments.py.
    """
    csv_path = _DATA / "sector_map.csv"
    if csv_path.exists():
        result: dict[str, str] = {}
        with csv_path.open() as f:
            for row in csv.DictReader(f):
                result[row["symbol"]] = row["sector"]
        return result

    # Fallback: NIFTY 50 hardcoded table.
    return {sym: sec for _, sym, sec in _NIFTY50_FALLBACK}


@lru_cache
def all_instrument_keys() -> list[str]:
    """Upstox instrument_keys for the full tradeable universe.

    Loads from data/instruments.json if available (generated by
    scripts/seed_instruments.py), otherwise falls back to NIFTY 50 only.
    """
    js = _load_json()
    if js.get("instrument_keys"):
        return js["instrument_keys"]

    csv_path = _DATA / "instruments.csv"
    if csv_path.exists():
        keys: list[str] = []
        with csv_path.open() as f:
            for row in csv.DictReader(f):
                if row.get("instrument_type", "").upper() == "EQ":
                    keys.append(row["instrument_key"])
        if keys:
            return keys

    # Fallback: NIFTY 50 instrument keys only.
    return [ikey for ikey, _, _ in _NIFTY50_FALLBACK]


@lru_cache
def _key_to_symbol() -> dict[str, str]:
    """Build instrument_key → short symbol mapping."""
    js = _load_json()
    if js.get("key_to_symbol"):
        return js["key_to_symbol"]

    csv_path = _DATA / "instruments.csv"
    if csv_path.exists():
        mapping: dict[str, str] = {}
        with csv_path.open() as f:
            for row in csv.DictReader(f):
                if row.get("instrument_type", "").upper() == "EQ":
                    exch = row.get("exchange", "NSE")
                    mapping[row["instrument_key"]] = f"{exch}:{row['tradingsymbol']}"
        if mapping:
            return mapping

    return {ikey: sym for ikey, sym, _ in _NIFTY50_FALLBACK}


def to_symbol(instrument_key: str) -> str:
    """Convert Upstox instrument_key to short trading symbol.

    e.g. "NSE_EQ|INE002A01018" → "NSE:RELIANCE"
    """
    return _key_to_symbol().get(instrument_key, instrument_key)
